# Generated by Django 4.2.10 on 2024-03-08 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message_Name', models.CharField(max_length=25)),
                ('Message', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.CharField(max_length=20)),
                ('Number', models.CharField(max_length=10)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Curfew_Applies', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cq_Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duty_Name', models.CharField(max_length=25)),
                ('Duties', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'CQ Duties',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('Duty_Day_Curfew_From', models.TimeField(blank=True, null=True)),
                ('Duty_Day_Curfew_To', models.TimeField(blank=True, null=True)),
                ('Non_Duty_Day_Curfew_From', models.TimeField(blank=True, null=True)),
                ('Non_Duty_Day_Curfew_To', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('E', 'E'), ('O', 'O'), ('Civilian', 'Civilian'), ('Other', 'Other')], max_length=15)),
                ('Grade', models.CharField(choices=[('N/A', 'N/A'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=5)),
                ('Rank_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_Name', models.CharField(max_length=25)),
                ('Quick_Reference', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule_Name', models.CharField(max_length=20)),
                ('Monday', models.CharField(choices=[('Duty Day', 'Duty Day'), ('Non Duty Day', 'Non Duty Day')], max_length=15)),
                ('Tuesday', models.CharField(choices=[('Duty Day', 'Duty Day'), ('Non Duty Day', 'Non Duty Day')], max_length=15)),
                ('Wednesday', models.CharField(choices=[('Duty Day', 'Duty Day'), ('Non Duty Day', 'Non Duty Day')], max_length=15)),
                ('Thursday', models.CharField(choices=[('Duty Day', 'Duty Day'), ('Non Duty Day', 'Non Duty Day')], max_length=15)),
                ('Friday', models.CharField(choices=[('Duty Day', 'Duty Day'), ('Non Duty Day', 'Non Duty Day')], max_length=15)),
                ('Saturday', models.CharField(choices=[('Duty Day', 'Duty Day'), ('Non Duty Day', 'Non Duty Day')], max_length=15)),
                ('Sunday', models.CharField(choices=[('Duty Day', 'Duty Day'), ('Non Duty Day', 'Non Duty Day')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': "Status'",
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(default='Please Enter CAC UUID', max_length=25)),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('Service', models.CharField(choices=[('USAF', 'USAF'), ('ARMY', 'ARMY'), ('USN', 'USN'), ('USMC', 'USMC'), ('USCG', 'USCG'), ('USSF', 'USSF'), ('Civilian', 'Civilian'), ('Other', 'Other')], max_length=10)),
                ('Active_Status', models.CharField(choices=[('Active Duty', 'Active Duty'), ('Guard', 'Guard'), ('Reserve', 'Reserve'), ('N/A', 'N/A')], max_length=20)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_of_Arrival', models.DateField(default=datetime.date(2024, 3, 7))),
                ('Room', models.IntegerField()),
                ('Work_Order', models.BooleanField(default=False)),
                ('Work_Order_Note', models.TextField(blank=True, null=True)),
                ('Commanders_Pass', models.BooleanField(default=False)),
                ('Form_4392', models.BooleanField(default=False)),
                ('Checked_In', models.BooleanField(default=False)),
                ('In_Out_Time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 8, 18, 45, 4, 440253, tzinfo=datetime.timezone.utc), null=True)),
                ('Time_24_hr', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 9, 18, 45, 4, 440325, tzinfo=datetime.timezone.utc), null=True)),
                ('Building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm_manager.building')),
                ('Phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm_manager.phase')),
                ('Rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm_manager.rank')),
                ('Schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm_manager.schedule')),
                ('Specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm_manager.specialty')),
                ('Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm_manager.status')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_of_Occurence', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 8, 18, 45, 4, 443026, tzinfo=datetime.timezone.utc), null=True)),
                ('In_or_Out', models.BooleanField(default=False)),
                ('Curfew_Broken', models.BooleanField(default=False)),
                ('Time_24_hr_Broken', models.BooleanField(default=False)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm_manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scan_Time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 8, 18, 45, 4, 444458, tzinfo=datetime.timezone.utc), null=True)),
                ('In_or_Out', models.BooleanField(default=False)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm_manager.student')),
            ],
        ),
    ]
