# Generated by Django 4.2.10 on 2024-03-08 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='In_Out_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 8, 18, 53, 2, 567194, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Time_24_hr',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 9, 18, 53, 2, 567269, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='Scan_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 8, 18, 53, 2, 571428, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='Time_of_Occurence',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 8, 18, 53, 2, 569927, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
