# Generated by Django 4.2.10 on 2024-03-11 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_manager', '0002_alter_student_in_out_time_alter_student_time_24_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Date_of_Arrival',
            field=models.DateField(default=datetime.date(2024, 3, 10)),
        ),
        migrations.AlterField(
            model_name='student',
            name='In_Out_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 11, 14, 5, 32, 31766, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Time_24_hr',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 12, 14, 5, 32, 31839, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='Scan_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 11, 14, 5, 32, 36067, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='Time_of_Occurence',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 11, 14, 5, 32, 34663, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
