# Generated by Django 4.2.10 on 2024-03-04 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duty_Name', models.CharField(max_length=25)),
                ('Duties', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_Name', models.CharField(max_length=25)),
                ('Quick_Reference', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(default='Please Enter CAC UUID', max_length=25)),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('AFSC', models.CharField(choices=[('3E7x1', '3E7x1'), ('9S100', '9S100')], max_length=10)),
                ('Rank', models.CharField(choices=[('AB', 'AB'), ('AMN', 'AMN'), ('A1C', 'A1C'), ('SRA', 'SRA')], max_length=10)),
                ('Service', models.CharField(choices=[('USAF', 'USAF'), ('ARMY', 'ARMY'), ('USN', 'USN'), ('USMC', 'USMC'), ('USCG', 'USCG'), ('USSF', 'USSF')], max_length=10)),
                ('Active_Status', models.CharField(choices=[('Active Duty', 'Active Duty'), ('Guard', 'Guard'), ('Reserve', 'Reserve')], max_length=20)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_of_Arrival', models.DateField(default=datetime.date(2024, 3, 3))),
                ('Building', models.CharField(choices=[('MODS', 'MODS'), ('3126 - 312th', '3126 - 312th'), ('3135 - 315th', '3135 - 315th'), ('3139 - 316th', '3139 - 316th')], max_length=20)),
                ('Room', models.IntegerField()),
                ('Work_Order', models.BooleanField(default=False)),
                ('Work_Order_Note', models.TextField(blank=True, null=True)),
                ('Phase', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('Status', models.CharField(choices=[('Casuals', 'Casuals'), ('Student', 'Student'), ('Graduated', 'Graduated'), ('Reclass', 'Reclass'), ('CQ', 'CQ')], max_length=20)),
                ('Commander_Pass', models.BooleanField(default=False)),
                ('Form_4392', models.BooleanField(default=False)),
                ('Checked_In', models.BooleanField(default=False)),
                ('In_Out_Time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 19, 21, 40, 250778, tzinfo=datetime.timezone.utc), null=True)),
                ('Time_24_hr', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 5, 19, 21, 40, 250842, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scan_Time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 19, 21, 40, 254634, tzinfo=datetime.timezone.utc), null=True)),
                ('In_or_Out', models.BooleanField(default=False)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.student')),
            ],
        ),
        migrations.CreateModel(
            name='Curfew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_of_Occurence', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 19, 21, 40, 253276, tzinfo=datetime.timezone.utc), null=True)),
                ('In_or_Out', models.BooleanField(default=False)),
                ('Curfew_Broken', models.BooleanField(default=False)),
                ('Time_24_hr_Broken', models.BooleanField(default=False)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.student')),
            ],
        ),
    ]
