# Generated by Django 4.2.10 on 2024-03-04 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curfew',
            name='Time_of_Occurence',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 19, 22, 15, 682691, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='In_Out_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 19, 22, 15, 680320, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Time_24_hr',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 5, 19, 22, 15, 680374, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='Scan_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 19, 22, 15, 684128, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
