# Generated by Django 4.2.10 on 2024-03-04 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_alter_curfew_time_of_occurence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curfew',
            name='Time_of_Occurence',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 19, 34, 8, 387345, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='In_Out_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 19, 34, 8, 384964, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Time_24_hr',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 5, 19, 34, 8, 385029, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='Scan_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 19, 34, 8, 388863, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
